admin_name: admin
admin_pwd: 3040434A4556
cookie_secret: htFuvC9FTDanupmQdFFgMYWghPlFaEzZjLMfxtMtUkg
db_echo: true
db_pool: 50
db_url: sqlite:///database.sqlite3
debug: true
host_file: hosts
logfile: /var/log/surelink-oms.log
login_url: /manage/login
nagios_bin: /usr/sbin/nagios
nagios_cfg: /etc/nagios/nagios.cfg
nagios_host_cfg_dir: /etc/nagios/servers
nagios_host_group_cfg: /etc/nagios/objects/hostgroups.cfg
nagios_service: nagios
page_size: 10
static_path: ./static
system_name: !!python/str "ToughNag\u8FD0\u7EF4\u7BA1\u7406\u7CFB\u7EDF"
test: true
version: '1.0'
xsrf_cookies: false
